(MainThread) 190906_11:41:14.262 DEBUG Trading.py:133 now is 2019-09-06 11:41:14.262743
(MainThread) 190906_11:41:17.114 ERROR wrapper.py:56 ERROR -1 2104 Market data farm connection is OK:usfarm.nj
(MainThread) 190906_11:41:17.116 ERROR wrapper.py:56 ERROR -1 2104 Market data farm connection is OK:usfarm
(MainThread) 190906_11:41:17.117 ERROR wrapper.py:56 ERROR -1 2106 HMDS data farm connection is OK:ushmds
(Thread-1) 190906_11:41:28.613 ERROR reader.py:52 unhandled exception in EReader thread
Traceback (most recent call last):
  File "d:\py\tms\ibapi\reader.py", line 34, in run
    data = self.conn.recvMsg()
  File "d:\py\tms\ibapi\connection.py", line 99, in recvMsg
    buf = self._recvAllMsg()
  File "d:\py\tms\ibapi\connection.py", line 119, in _recvAllMsg
    buf = self.socket.recv(4096)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
(Thread-2) 190906_11:42:25.136 ERROR wrapper.py:56 ERROR 5 504 Not connected
(Thread-2) 190906_11:43:45.448 ERROR wrapper.py:56 ERROR 6 504 Not connected
(Thread-2) 190906_11:43:49.471 ERROR wrapper.py:56 ERROR 7 504 Not connected
